#' @name getED
#' @title Accessor to retrieve the numeric median effective dose from a skrmdb object
#' @description This is an accessor function for retrieving the numeric value of the effective 
#' median dose from a skrmdb object object generated by ReedMuench, SpearKarb or DragBehr
#' @usage getED(x)
#' @param x class skrmdb
#' @rdname skrmdb-class
#' @export
#' @author \link{skrmdb-object}
#' @example
#' temp <- DragBehr(y=c(0,3,5,8,10,10), n=rep(10,6), x=1:6)
#' getED(temp)
getED = function(x) {
  return(as.numeric(x$ed))
}

#' @name getdata
#' @title Accessor to retrieve the the data used in the call to create an skrmdb object
#' @description This is an accessor function for retrieving the data used to compute the effective 
#' median dose from a skrmdb object object generated by ReedMuench, SpearKarb or DragBehr
#' @usage getdata(x)
#' @param x class skrmdb
#' @rdname skrmdb-class
#' @export
#' @author \link{skrmdb-object}
#' @example
#' temp <- DragBehr(y=c(0,3,5,8,10,10), n=rep(10,6), x=1:6)
#' getdata(temp)
getdata = function(x) {
  return(as.data.frame(A))
}

print.skrmdb <- function(x, ...) {
  if (length(x$ed) == 0) {
    cat("empty construct\n")
  } else {
    cat(paste("ED50 by the", x$eval, "method\n"))
    cat("ed:  ", signif(x$ed, digits = 3), "\n")
    if (x$eval == "SpearKarb") {
      cat(paste("var: ", signif(x$var, digits = 3), "\n"))
    }
    if (!is.null(x$messages)) {
      cat("\n")
      cat(paste0(x$messages, collapse = "\n"))
    }
  }
  invisible(x)
}

#' @title Class definition for skrmdb object
#' @description The skrmdb object holds output from functions in the skrmdb package.
#' @details
#' \describe{
#' 		\item{\code{eval}}{Evaluation method. One of 'ReedMuench', 'SpearKarb',  or 'DragBehr'. character string.}
#' 		\item{\code{ed}}{Median effective dose by eval method. numeric.}
#' 		\item{\code{var}}{Variance (for Spearman-Kärber method only). numeric.}
#' 		\item{\code{A}}{The data used to compute the effective median dose. data.frame, numeric.}
#' 		\item{\code{message}}{Messages and warnings generated durning the calculation. character string}
#' }
#' @name skrmdb-class
#' @author \link{skrmdb-package}
new_skrmdb <- function(eval = character(), A, 
                       ed = numeric(), 
                       var = NA_real_) {
  messages = character()
  if (attr(A, "warning.reverse")) {
    messages = c(messages, "* Order of data was reversed.")
  }
  if (attr(A, "warning.uneven")) {
    messages = c(messages, "* Uneven dilution scheme.")
  }
  if (attr(A, "warning.monotone")) {
    messages = c(messages, "* y is not monotonic. ED50 may be unreliable.")
  }
  if (attr(A, "warning.bracket")) {
    messages = c(messages, "* Dilutions fail to bracket the midpoint. ED50 is unreliable.")
  }
  structure(list(eval = eval, 
                 ed   = ed, 
                 var  = var, 
                 A    = as.data.frame(A),
                 messages = messages),
            class = "skrmdb")
}

